name: Reusable Kubernetes Deploy

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      deployment_type:
        required: false
        type: string
        default: "helm"
      custom:
        required: false
        type: boolean
        default: false
      helm_repository:
        required: false
        type: string
      helm_chart:
        required: false
        type: string
      helm_version:
        required: false
        type: string
      values_path:
        required: false
        type: string
        default: "helm/values"
      ingress_domain:
        required: true
        type: string
    secrets:
      KUBE_CONFIG_DEV:
        required: true
      KUBE_CONFIG_LIVE:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - stage: dev
            environment: Development
            kubeconfig: KUBE_CONFIG_DEV
          - stage: live
            environment: Production
            kubeconfig: KUBE_CONFIG_LIVE
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Setup Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.9.3
        with:
          kubectl: "1.27.3"
          helm: "3.12.3"

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets[matrix.kubeconfig] }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Run deployment script
        run: |
          go run deploy/main.go \
            --stage ${{ matrix.stage }} \
            --env ${{ matrix.environment }} \
            --app ${{ inputs.app_name }} \
            --pr ${{ github.event.pull_request.number || '' }} \
            --values ${{ inputs.values_path }} \
            --custom ${{ inputs.custom }} \
            --chart ${{ inputs.helm_chart }} \
            --version ${{ inputs.helm_version }} \
            --repo ${{ inputs.helm_repository }} \
            --domain ${{ inputs.ingress_domain }}

      - name: Cleanup Kubeconfig
        if: always()
        run: rm -f ~/.kube/config
